config/routes.rb
Rails.application.routes.draw do
  resources :bets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root :to => 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
class Bet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bet_controller.rb
require 'open-uri'
class BetController < ApplicationController
    
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_action :set_bet, only: [:show, :edit, :update, :destroy]

  # GET /bets
  # GET /bets.json
  def index
    @bets = Bet.all
  end

  # GET /bets/1
  # GET /bets/1.json
  def show
  end

  # GET /bets/new
  def new
    @bet = Bet.new
  end

  # GET /bets/1/edit
  def edit
  end

  # POST /bets
  # POST /bets.json
  def create
    @bet = Bet.new(bet_params)

    respond_to do |format|
      if @bet.save
        format.html { redirect_to @bet, notice: 'Bet was successfully created.' }
        format.json { render :show, status: :created, location: @bet }
      else
        format.html { render :new }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bets/1
  # PATCH/PUT /bets/1.json
  def update
    respond_to do |format|
      if @bet.update(bet_params)
        format.html { redirect_to @bet, notice: 'Bet was successfully updated.' }
        format.json { render :show, status: :ok, location: @bet }
      else
        format.html { render :edit }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bets/1
  # DELETE /bets/1.json
  def destroy
    @bet.destroy
    respond_to do |format|
      format.html { redirect_to bets_url, notice: 'Bet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bet
      @bet = Bet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bet_params
      params.require(:bet).permit(:date, :fighter, :odds, :margin)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bet_helper.rb
module BetHelper
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bets/_form.html.erb
<%= form_with(model: bet, local: true) do |form| %>
  <% if bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% bet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date, id: :bet_date %>
  </div>

  <div class="field">
    <%= form.label :fighter %>
    <%= form.text_field :fighter, id: :bet_fighter %>
  </div>

  <div class="field">
    <%= form.label :odds %>
    <%= form.text_field :odds, id: :bet_odds %>
  </div>

  <div class="field">
    <%= form.label :margin %>
    <%= form.text_field :margin, id: :bet_margin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Editing Bet</h1>

<%= render 'form', bet: @bet %>

<%= link_to 'Show', @bet %> |
<%= link_to 'Back', bets_path %>

app/views/bets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bets</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Fighter</th>
      <th>Odds</th>
      <th>Margin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bets.each do |bet| %>
      <tr>
        <td><%= bet.date %></td>
        <td><%= bet.fighter %></td>
        <td><%= bet.odds %></td>
        <td><%= bet.margin %></td>
        <td><%= link_to 'Show', bet %></td>
        <td><%= link_to 'Edit', edit_bet_path(bet) %></td>
        <td><%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bet', new_bet_path %>

app/views/bets/new.html.erb
<h1>New Bet</h1>

<%= render 'form', bet: @bet %>

<%= link_to 'Back', bets_path %>

app/views/bets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @bet.date %>
</p>

<p>
  <strong>Fighter:</strong>
  <%= @bet.fighter %>
</p>

<p>
  <strong>Odds:</strong>
  <%= @bet.odds %>
</p>

<p>
  <strong>Margin:</strong>
  <%= @bet.margin %>
</p>

<%= link_to 'Edit', edit_bet_path(@bet) %> |
<%= link_to 'Back', bets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Betr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1> Hi! </h1>